name: CI com SonarQube e MantisHub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  sonar_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c칩digo
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Executar SonarScanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=meu-projeto \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Verificar resultado da an치lise
        id: verifica_qualidade
        run: |
          sleep 10  # tempo para o Sonar processar
          resposta=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
            "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=meu-projeto")
          
          echo "$resposta"
          status=$(echo "$resposta" | jq -r .projectStatus.status)
          echo "Qualidade: $status"
          echo "::set-output name=gate_status::$status"

      - name: Criar issue no MantisHub se falhou
        if: steps.verifica_qualidade.outputs.gate_status != 'OK'
        run: |
          curl -X POST https://asssossiacaodotesaodeolaria.mantishub.io/api/rest/issues/ \
            -H "Authorization: ${{ secrets.MANTIS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "summary": "Falha na an치lise do SonarQube",
              "description": "O projeto falhou na an치lise do quality gate.\nVeja detalhes em: '${{ secrets.SONAR_HOST_URL }}/dashboard?id=meu-projeto'",
              "project": { "id": 1 },
              "category": "general",
              "severity": "major"
            }'